spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: abraham27
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: false

server:
  port: 8080
